esphome:
  name: $devicename

substitutions:
  devicename: "tpms-01"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api: 

esp32_ble_tracker:
  scan_parameters:
    active: false

packages:
  fl: !include
    file: tpms-module.yaml
    vars:
      name_prefix: "$devicename FL"
      id_slug: fl
      mac: !secret fl_mac
  fr: !include
    file: tpms-module.yaml
    vars:
      name_prefix: "$devicename FR"
      id_slug: fr
      mac: !secret fr_mac
  rl: !include
    file: tpms-module.yaml
    vars:
      name_prefix: "$devicename RL"
      id_slug: rl
      mac: !secret rl_mac
  rr: !include
    file: tpms-module.yaml
    vars:
      name_prefix: "$devicename RR"
      id_slug: rr
      mac: !secret rr_mac
